import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';

const SOURCES_DIR = path.resolve('sources');

const newKeys: Record<string, Record<string, string>> = {
  importTranslations: {
    'zh-CN': '导入翻译',
    'zh-TW': '導入翻譯',
    'en-US': 'Import Translations',
    'ja-JP': '翻訳をインポート',
    'ko-KR': '번역 가져오기',
    'fr-FR': 'Importer les traductions',
    'de-DE': 'Übersetzungen importieren',
    'es-ES': 'Importar traducciones',
    'it-IT': 'Importa traduzioni',
    'pt-PT': 'Importar traduções',
    'ru-RU': 'Импорт переводов',
    'ar-SA': 'استيراد الترجمات',
    'hi-IN': 'अनुवाद आयात करें',
    'vi-VN': 'Nhập bản dịch',
    'th-TH': 'นำเข้าคำแปล',
  },
  importLabel: {
    'zh-CN': '导入翻译文件',
    'zh-TW': '導入翻譯文件',
    'en-US': 'Import Translation File',
    'ja-JP': '翻訳ファイルをインポート',
    'ko-KR': '번역 파일 가져오기',
    'fr-FR': 'Importer un fichier de traduction',
    'de-DE': 'Übersetzungsdatei importieren',
    'es-ES': 'Importar archivo de traducción',
    'it-IT': 'Importa file di traduzione',
    'pt-PT': 'Importar ficheiro de tradução',
    'ru-RU': 'Импортировать файл перевода',
    'ar-SA': 'استيراد ملف الترجمة',
    'hi-IN': 'अनुवाद फ़ाइल आयात करें',
    'vi-VN': 'Nhập tệp bản dịch',
    'th-TH': 'นำเข้าไฟล์คำแปล',
  },
  importDesc: {
    'zh-CN': '导入自定义翻译文件以覆盖应用的默认翻译',
    'zh-TW': '導入自定義翻譯文件以覆蓋應用的默認翻譯',
    'en-US': 'Import a custom translation file to override the app\'s default translations',
    'ja-JP': 'カスタム翻訳ファイルをインポートしてアプリのデフォルト翻訳を上書きします',
    'ko-KR': '사용자 정의 번역 파일을 가져와 앱의 기본 번역을 덮어씁니다',
    'fr-FR': 'Importer un fichier de traduction personnalisé pour remplacer les traductions par défaut',
    'de-DE': 'Benutzerdefinierte Übersetzungsdatei importieren, um Standardübersetzungen zu überschreiben',
    'es-ES': 'Importar un archivo de traducción personalizado para sobrescribir las traducciones predeterminadas',
    'it-IT': 'Importa un file di traduzione personalizzato per sovrascrivere le traduzioni predefinite',
    'pt-PT': 'Importar um ficheiro de tradução personalizado para substituir as traduções padrão',
    'ru-RU': 'Импортируйте файл перевода, чтобы переопределить переводы по умолчанию',
    'ar-SA': 'استيراد ملف ترجمة مخصص لتجاوز الترجمات الافتراضية للتطبيق',
    'hi-IN': 'डिफ़ॉल्ट अनुवादों को ओवरराइड करने के लिए एक कस्टम अनुवाद फ़ाइल आयात करें',
    'vi-VN': 'Nhập tệp bản dịch tùy chỉnh để ghi đè bản dịch mặc định của ứng dụng',
    'th-TH': 'นำเข้าไฟล์คำแปลที่กำหนดเองเพื่อแทนที่คำแปลเริ่มต้นของแอป',
  },
  importButton: {
    'zh-CN': '选择文件',
    'zh-TW': '選擇文件',
    'en-US': 'Select File',
    'ja-JP': 'ファイルを選択',
    'ko-KR': '파일 선택',
    'fr-FR': 'Sélectionner un fichier',
    'de-DE': 'Datei auswählen',
    'es-ES': 'Seleccionar archivo',
    'it-IT': 'Seleziona file',
    'pt-PT': 'Selecionar ficheiro',
    'ru-RU': 'Выбрать файл',
    'ar-SA': 'اختيار ملف',
    'hi-IN': 'फ़ाइल चुनें',
    'vi-VN': 'Chọn tệp',
    'th-TH': 'เลือกไฟล์',
  },
  clearLabel: {
    'zh-CN': '清除自定义翻译',
    'zh-TW': '清除自定義翻譯',
    'en-US': 'Clear Custom Translations',
    'ja-JP': 'カスタム翻訳をクリア',
    'ko-KR': '사용자 정의 번역 지우기',
    'fr-FR': 'Effacer les traductions personnalisées',
    'de-DE': 'Benutzerdefinierte Übersetzungen löschen',
    'es-ES': 'Borrar traducciones personalizadas',
    'it-IT': 'Cancella traduzioni personalizzate',
    'pt-PT': 'Limpar traduções personalizadas',
    'ru-RU': 'Очистить пользовательские переводы',
    'ar-SA': 'مسح الترجمات المخصصة',
    'hi-IN': 'कस्टम अनुवाद साफ़ करें',
    'vi-VN': 'Xóa bản dịch tùy chỉnh',
    'th-TH': 'ล้างคำแปลที่กำหนดเอง',
  },
  clearDesc: {
    'zh-CN': '移除所有已导入的自定义翻译，恢复为应用的默认翻译',
    'zh-TW': '移除所有已導入的自定義翻譯，恢復為應用的默認翻譯',
    'en-US': 'Remove all imported custom translations and restore defaults',
    'ja-JP': 'インポートしたカスタム翻訳をすべて削除し、デフォルトに戻します',
    'ko-KR': '가져온 모든 사용자 정의 번역을 제거하고 기본값으로 복원합니다',
    'fr-FR': 'Supprimer toutes les traductions personnalisées importées et restaurer les valeurs par défaut',
    'de-DE': 'Alle importierten benutzerdefinierten Übersetzungen entfernen und Standard wiederherstellen',
    'es-ES': 'Eliminar todas las traducciones personalizadas importadas y restaurar los valores predeterminados',
    'it-IT': 'Rimuovi tutte le traduzioni personalizzate importate e ripristina quelle predefinite',
    'pt-PT': 'Remover todas as traduções personalizadas importadas e restaurar as predefinições',
    'ru-RU': 'Удалить все импортированные переводы и восстановить стандартные',
    'ar-SA': 'إزالة جميع الترجمات المخصصة المستوردة واستعادة الإعدادات الافتراضية',
    'hi-IN': 'सभी आयातित कस्टम अनुवाद हटाएं और डिफ़ॉल्ट पुनर्स्थापित करें',
    'vi-VN': 'Xóa tất cả bản dịch tùy chỉnh đã nhập và khôi phục mặc định',
    'th-TH': 'ลบคำแปลที่กำหนดเองที่นำเข้าทั้งหมดและคืนค่าเริ่มต้น',
  },
  clearButton: {
    'zh-CN': '清除',
    'zh-TW': '清除',
    'en-US': 'Clear',
    'ja-JP': 'クリア',
    'ko-KR': '지우기',
    'fr-FR': 'Effacer',
    'de-DE': 'Löschen',
    'es-ES': 'Borrar',
    'it-IT': 'Cancella',
    'pt-PT': 'Limpar',
    'ru-RU': 'Очистить',
    'ar-SA': 'مسح',
    'hi-IN': 'साफ़ करें',
    'vi-VN': 'Xóa',
    'th-TH': 'ล้าง',
  },
  importSuccess: {
    'zh-CN': '翻译导入成功',
    'zh-TW': '翻譯導入成功',
    'en-US': 'Translations imported successfully',
    'ja-JP': '翻訳のインポートに成功しました',
    'ko-KR': '번역을 성공적으로 가져왔습니다',
    'fr-FR': 'Traductions importées avec succès',
    'de-DE': 'Übersetzungen erfolgreich importiert',
    'es-ES': 'Traducciones importadas correctamente',
    'it-IT': 'Traduzioni importate con successo',
    'pt-PT': 'Traduções importadas com sucesso',
    'ru-RU': 'Переводы успешно импортированы',
    'ar-SA': 'تم استيراد الترجمات بنجاح',
    'hi-IN': 'अनुवाद सफलतापूर्वक आयात किए गए',
    'vi-VN': 'Đã nhập bản dịch thành công',
    'th-TH': 'นำเข้าคำแปลสำเร็จแล้ว',
  },
  clearSuccess: {
    'zh-CN': '自定义翻译已清除',
    'zh-TW': '自定義翻譯已清除',
    'en-US': 'Custom translations cleared',
    'ja-JP': 'カスタム翻訳をクリアしました',
    'ko-KR': '사용자 정의 번역이 지워졌습니다',
    'fr-FR': 'Traductions personnalisées effacées',
    'de-DE': 'Benutzerdefinierte Übersetzungen gelöscht',
    'es-ES': 'Traducciones personalizadas borradas',
    'it-IT': 'Traduzioni personalizzate cancellate',
    'pt-PT': 'Traduções personalizadas limpas',
    'ru-RU': 'Пользовательские переводы очищены',
    'ar-SA': 'تم مسح الترجمات المخصصة',
    'hi-IN': 'कस्टम अनुवाद साफ़ कर दिए गए हैं',
    'vi-VN': 'Đã xóa bản dịch tùy chỉnh',
    'th-TH': 'ล้างคำแปลที่กำหนดเองแล้ว',
  },
  importError: {
    'zh-CN': '导入失败，请检查文件格式',
    'zh-TW': '導入失敗，請檢查文件格式',
    'en-US': 'Import failed, please check the file format',
    'ja-JP': 'インポートに失敗しました。ファイル形式を確認してください',
    'ko-KR': '가져오기 실패, 파일 형식을 확인하세요',
    'fr-FR': 'Échec de l\'importation, vérifiez le format du fichier',
    'de-DE': 'Import fehlgeschlagen, bitte Dateiformat prüfen',
    'es-ES': 'Error al importar, compruebe el formato del archivo',
    'it-IT': 'Importazione fallita, controlla il formato del file',
    'pt-PT': 'Falha na importação, verifique o formato do ficheiro',
    'ru-RU': 'Ошибка импорта, проверьте формат файла',
    'ar-SA': 'فشل الاستيراد، يرجى التحقق من تنسيق الملف',
    'hi-IN': 'आयात विफल, कृपया फ़ाइल प्रारूप जांचें',
    'vi-VN': 'Nhập thất bại, vui lòng kiểm tra định dạng tệp',
    'th-TH': 'การนำเข้าล้มเหลว โปรดตรวจสอบรูปแบบไฟล์',
  },
  noImportedTranslations: {
    'zh-CN': '暂无已导入的翻译',
    'zh-TW': '暫無已導入的翻譯',
    'en-US': 'No imported translations',
    'ja-JP': 'インポートされた翻訳はありません',
    'ko-KR': '가져온 번역이 없습니다',
    'fr-FR': 'Aucune traduction importée',
    'de-DE': 'Keine importierten Übersetzungen',
    'es-ES': 'No hay traducciones importadas',
    'it-IT': 'Nessuna traduzione importata',
    'pt-PT': 'Nenhuma tradução importada',
    'ru-RU': 'Нет импортированных переводов',
    'ar-SA': 'لا توجد ترجمات مستوردة',
    'hi-IN': 'कोई आयातित अनुवाद नहीं',
    'vi-VN': 'Không có bản dịch nào được nhập',
    'th-TH': 'ไม่มีคำแปลที่นำเข้า',
  },
  removeSuccess: {
    'zh-CN': '已删除',
    'zh-TW': '已刪除',
    'en-US': 'Removed',
    'ja-JP': '削除しました',
    'ko-KR': '삭제됨',
    'fr-FR': 'Supprimé',
    'de-DE': 'Entfernt',
    'es-ES': 'Eliminado',
    'it-IT': 'Rimosso',
    'pt-PT': 'Removido',
    'ru-RU': 'Удалено',
    'ar-SA': 'تمت الإزالة',
    'hi-IN': 'हटा दिया गया',
    'vi-VN': 'Đã xóa',
    'th-TH': 'ลบแล้ว',
  },
  removeError: {
    'zh-CN': '删除失败',
    'zh-TW': '刪除失敗',
    'en-US': 'Failed to remove',
    'ja-JP': '削除に失敗しました',
    'ko-KR': '삭제 실패',
    'fr-FR': 'Échec de la suppression',
    'de-DE': 'Entfernen fehlgeschlagen',
    'es-ES': 'Error al eliminar',
    'it-IT': 'Rimozione fallita',
    'pt-PT': 'Falha ao remover',
    'ru-RU': 'Не удалось удалить',
    'ar-SA': 'فشلت الإزالة',
    'hi-IN': 'हटाने में विफल',
    'vi-VN': 'Xóa thất bại',
    'th-TH': 'ลบล้มเหลว',
  },
  customLabel: {
    'zh-CN': '已导入',
    'zh-TW': '已導入',
    'en-US': 'Imported',
    'ja-JP': 'インポート済み',
    'ko-KR': '가져옴',
    'fr-FR': 'Importé',
    'de-DE': 'Importiert',
    'es-ES': 'Importado',
    'it-IT': 'Importato',
    'pt-PT': 'Importado',
    'ru-RU': 'Импортирован',
    'ar-SA': 'تم الاستيراد',
    'hi-IN': 'आयातित',
    'vi-VN': 'Đã nhập',
    'th-TH': 'นำเข้าแล้ว',
  },
  selectTranslationFile: {
    'zh-CN': '选择翻译文件',
    'zh-TW': '選擇翻譯文件',
    'en-US': 'Select Translation File',
    'ja-JP': '翻訳ファイルを選択',
    'ko-KR': '번역 파일 선택',
    'fr-FR': 'Sélectionner le fichier de traduction',
    'de-DE': 'Übersetzungsdatei auswählen',
    'es-ES': 'Seleccionar archivo de traducción',
    'it-IT': 'Seleziona file di traduzione',
    'pt-PT': 'Selecionar ficheiro de tradução',
    'ru-RU': 'Выберите файл перевода',
    'ar-SA': 'اختر ملف الترجمة',
    'hi-IN': 'अनुवाद फ़ाइल चुनें',
    'vi-VN': 'Chọn tệp bản dịch',
    'th-TH': 'เลือกไฟล์คำแปล',
  },
};

const langs = fs.readdirSync(SOURCES_DIR).filter(f =>
  fs.statSync(path.join(SOURCES_DIR, f)).isDirectory()
);

for (const lang of langs) {
  const settingsPath = path.join(SOURCES_DIR, lang, 'settings.yaml');
  if (!fs.existsSync(settingsPath)) continue;

  const content = yaml.load(fs.readFileSync(settingsPath, 'utf-8')) as Record<string, any>;

  for (const [key, translations] of Object.entries(newKeys)) {
    const value = translations[lang];
    if (value && content.settings && content.settings[key] === undefined) {
      content.settings[key] = value;
    }
  }

  fs.writeFileSync(settingsPath, yaml.dump(content, { lineWidth: 120, noRefs: true }));
  console.log(`Updated ${lang}/settings.yaml`);
}
